### ISSUE TITLE
Exports is not defined - using with grunt-contrib-jasmine

### ISSUE THREAD

**Issue by StephanBijzitter** [Updater/jasmine-fail-fast#1]
```
javascript
        jasmine: {
            test: {
                src: jasmineSrc,
                options: {
                    log: true,
                    summary: true,
                    display: 'none',
                    specs: [
                        'tests/**/*.spec.js'
                    ],
                    helpers: [
                        'node_modules/jasmine-fail-fast/dist/jasmine-fail-fast.js'
                    ]
                }
            }
        }
```

```
>> ReferenceError: Can't find variable: exports at
>> node_modules/jasmine-fail-fast/dist/jasmine-fail-fast.js:3
```

I am probably doing something wrong, and I guess it's not really a bug... but it is an issue :-)
How would I get this to work? Note that `jasmineSrc` is an array of files generated using my `node-file-parser` package https://bitbucket.org/skelware/node-file-parser/

Help would be appreciated, your package can save quite a lot of time upon test failure!

**Comment by pmowrer** [comment]
Hi @StephanBijzitter. I haven't used grunt in a while but hopefully I can help. First of all, this module isn't intended to be used as a helper directly. You'll want to create a separate helper JS file that `require`s the module and adds it as a reporter. Please see the README for details:
https://github.com/Updater/jasmine-fail-fast#as-a-jasmine-helper

**Comment by pmowrer** [comment]
Did that work for you @StephanBijzitter? Closing for now.
