### ISSUE TITLE
Lodash vulnerabilities

### ISSUE THREAD

**Issue by sumcoding** [Updater/jasmine-fail-fast#13]
https://nodesecurity.io/advisories/782      

Would be great to get this updated so that it is no longer listed as an issue for users of this.

**Comment by ynauls** [comment]
Is this project still maintained?

**Comment by pmowrer** [comment]
It hasn't been but hopefully will be soon assuming npm can finish transferring publishing rights to me

**Comment by pmowrer** [comment]
Closed by https://github.com/pmowrer/jasmine-fail-fast/pull/21
