### ISSUE TITLE
karma-jasmine-fail-fast-reporter

### ISSUE THREAD

**Issue by JamieMason** [Updater/jasmine-fail-fast#2]
Thanks for this utility @Updater, 
If anyone has the time and is interested, I just wanted to put in a request for a Karma Reporter to be created for jasmine-fail-fast.

There is a guide to [Developing Karma Plugins](http://karma-runner.github.io/0.12/dev/plugins.html).

Thanks.

**Comment by pmowrer** [comment]
Thanks @JamieMason. We don't have any internal use cases that combine karma and jasmine-fail-fast at the moment, but perhaps we'll work on a solution in the future. I'll be sure to post here in that case.

**Comment by michaelbull** [comment]
Apologies for the self-promotion, but I also ran into this issue and ended up writing it myself - however it doesn't depend on `jasmine-fail-fast`, it's more of a catch-all for any Karma errors.

https://github.com/MikeBull94/karma-fail-fast-reporter
