### ISSUE TITLE
What file is the "global Jasmine environment"?

### ISSUE THREAD

**Issue by pitymaia** [Updater/jasmine-fail-fast#9]
I trying to install it, but you say: "Add to the global Jasmine environment like so" I have no idea which jasmine file you are referring to. The documentation of jasmine also does not help at all and it seems that on the whole internet no one explains how to add a custom reporter to jasmine.

I do my angular tests with karma / jasmine and are getting ready for continuous integration, the fast-fail would help a lot, but I do not know where to call it.
In which file should I put the code?

Thanks.

**Comment by pmowrer** [comment]
Hello there! "Add to the global Jasmine environment like so" isn't a very helpful line. I'll remove it.

Are you using [`karma-jasmine`](https://github.com/karma-runner/karma-jasmine)?

**Comment by pitymaia** [comment]
Hi sorry for the delay, I took a few days off. Yes, I'm using karma-jasmine but I could not figure out where to put the code to make jasmine-fail-fast works.

**Comment by pmowrer** [comment]
Try the following:

```javascript
// karma.conf.js
var failFast = require('jasmine-fail-fast');

module.exports = function(config) {
  // Somewhere in your config block
  window.jasmine.getEnv().addReporter(failFast.init());
}
```

**Comment by pitymaia** [comment]
Thanks, that was very helpful.
